name: atm
description: A simple ATM CLI application.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Add your project dependencies here
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.0